name: Publish Any Commit

on:
  push:
    branches: [canary]
  pull_request:
    branches: [canary]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.30
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build:all
      - name: Publish commits
        run: bunx pkg-pr-new publish './packages/*'
